### PR TITLE
Check if JSON was properly decoded

### PR DESCRIPTION
**Pull request by alexymik**
Check if JSON was properly decoded before parsing system checks

### CODE REVIEW

**Comment by MegaphoneJon** [comment]
Thank you for the submission Alexy!  I'm going to test this right now.

**Comment by MegaphoneJon** [comment]
Hi Alexy - I can't figure out a scenario in which the JSON isn't properly decoded.  Can you please give me an example so I can test? Thanks!

**Comment by alexymik** [comment]
Hi,

In my case there was an unrelated PHP notice at the top of the output before the JSON output started. Adding that check let me see it and disable notices.

**Comment by MegaphoneJon** [comment]
Ah, OK.  I have this working now.  Thanks!

**Pull request merged**
